/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.ide;

import com.ge.research.sadl.darpa.aske.DialogRuntimeModule;
import com.ge.research.sadl.darpa.aske.DialogStandaloneSetup;
import com.ge.research.sadl.darpa.aske.ide.DialogIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DialogIdeSetup extends DialogStandaloneSetup {
  @Override
  public Injector createInjector() {
    DialogRuntimeModule _dialogRuntimeModule = new DialogRuntimeModule();
    DialogIdeModule _dialogIdeModule = new DialogIdeModule();
    return Guice.createInjector(Modules2.mixin(_dialogRuntimeModule, _dialogIdeModule));
  }
}
