/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.ide;

import com.ge.research.sadl.darpa.aske.ide.AbstractDialogIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DialogIdeModule extends AbstractDialogIdeModule {
}
