/*
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.services;

import com.ge.research.sadl.services.SADLGrammarAccess;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DialogGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DialogModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ge.research.sadl.darpa.aske.Dialog.DialogModel");
		private final RuleCall cSadlModelParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//DialogModel sadl::SadlModel:
		//	super::SadlModel;
		@Override public ParserRule getRule() { return rule; }
		
		//super::SadlModel
		public RuleCall getSadlModelParserRuleCall() { return cSadlModelParserRuleCall; }
	}
	public class SadlModelElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ge.research.sadl.darpa.aske.Dialog.SadlModelElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cCMKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Alternatives cAlternatives_0_1 = (Alternatives)cGroup_0.eContents().get(1);
		private final RuleCall cSadlStatementParserRuleCall_0_1_0 = (RuleCall)cAlternatives_0_1.eContents().get(0);
		private final RuleCall cEquationStatementParserRuleCall_0_1_1 = (RuleCall)cAlternatives_0_1.eContents().get(1);
		private final RuleCall cExternalEquationStatementParserRuleCall_0_1_2 = (RuleCall)cAlternatives_0_1.eContents().get(2);
		private final RuleCall cEOSParserRuleCall_0_2 = (RuleCall)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cCMKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cStringResponseParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final RuleCall cEOSParserRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final RuleCall cModifiedAskStatementParserRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final RuleCall cEOSParserRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final RuleCall cWhatStatementParserRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final RuleCall cEOSParserRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final RuleCall cHowManyValuesStatementParserRuleCall_4_0 = (RuleCall)cGroup_4.eContents().get(0);
		private final RuleCall cEOSParserRuleCall_4_1 = (RuleCall)cGroup_4.eContents().get(1);
		
		//@Override
		//SadlModelElement sadl::SadlModelElement:
		//	'CM:' (SadlStatement | EquationStatement | ExternalEquationStatement) EOS |
		//	'CM:' StringResponse EOS | ModifiedAskStatement EOS | WhatStatement EOS | HowManyValuesStatement EOS //|
		//	//	=>CMInput EOS
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'CM:' (SadlStatement | EquationStatement | ExternalEquationStatement) EOS | 'CM:' StringResponse EOS |
		//ModifiedAskStatement EOS | WhatStatement EOS | HowManyValuesStatement EOS
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'CM:' (SadlStatement | EquationStatement | ExternalEquationStatement) EOS
		public Group getGroup_0() { return cGroup_0; }
		
		//'CM:'
		public Keyword getCMKeyword_0_0() { return cCMKeyword_0_0; }
		
		//SadlStatement | EquationStatement | ExternalEquationStatement
		public Alternatives getAlternatives_0_1() { return cAlternatives_0_1; }
		
		//SadlStatement
		public RuleCall getSadlStatementParserRuleCall_0_1_0() { return cSadlStatementParserRuleCall_0_1_0; }
		
		//EquationStatement
		public RuleCall getEquationStatementParserRuleCall_0_1_1() { return cEquationStatementParserRuleCall_0_1_1; }
		
		//ExternalEquationStatement
		public RuleCall getExternalEquationStatementParserRuleCall_0_1_2() { return cExternalEquationStatementParserRuleCall_0_1_2; }
		
		//EOS
		public RuleCall getEOSParserRuleCall_0_2() { return cEOSParserRuleCall_0_2; }
		
		//'CM:' StringResponse EOS
		public Group getGroup_1() { return cGroup_1; }
		
		//'CM:'
		public Keyword getCMKeyword_1_0() { return cCMKeyword_1_0; }
		
		//StringResponse
		public RuleCall getStringResponseParserRuleCall_1_1() { return cStringResponseParserRuleCall_1_1; }
		
		//EOS
		public RuleCall getEOSParserRuleCall_1_2() { return cEOSParserRuleCall_1_2; }
		
		//ModifiedAskStatement EOS
		public Group getGroup_2() { return cGroup_2; }
		
		//ModifiedAskStatement
		public RuleCall getModifiedAskStatementParserRuleCall_2_0() { return cModifiedAskStatementParserRuleCall_2_0; }
		
		//EOS
		public RuleCall getEOSParserRuleCall_2_1() { return cEOSParserRuleCall_2_1; }
		
		//WhatStatement EOS
		public Group getGroup_3() { return cGroup_3; }
		
		//WhatStatement
		public RuleCall getWhatStatementParserRuleCall_3_0() { return cWhatStatementParserRuleCall_3_0; }
		
		//EOS
		public RuleCall getEOSParserRuleCall_3_1() { return cEOSParserRuleCall_3_1; }
		
		////	WhatValuesStatement EOS	|
		//HowManyValuesStatement EOS
		public Group getGroup_4() { return cGroup_4; }
		
		////	WhatValuesStatement EOS	|
		//HowManyValuesStatement
		public RuleCall getHowManyValuesStatementParserRuleCall_4_0() { return cHowManyValuesStatementParserRuleCall_4_0; }
		
		//EOS
		public RuleCall getEOSParserRuleCall_4_1() { return cEOSParserRuleCall_4_1; }
	}
	public class StringResponseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ge.research.sadl.darpa.aske.Dialog.StringResponse");
		private final Assignment cStrAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStrSTRINGTerminalRuleCall_0 = (RuleCall)cStrAssignment.eContents().get(0);
		
		//StringResponse:
		//	str=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//str=STRING
		public Assignment getStrAssignment() { return cStrAssignment; }
		
		//STRING
		public RuleCall getStrSTRINGTerminalRuleCall_0() { return cStrSTRINGTerminalRuleCall_0; }
	}
	public class ModifiedAskStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ge.research.sadl.darpa.aske.Dialog.ModifiedAskStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModifiedAskStatementAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cAskKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cAskKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cExprAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cExprAlternatives_2_0 = (Alternatives)cExprAssignment_2.eContents().get(0);
		private final RuleCall cExprConstructExpressionParserRuleCall_2_0_0 = (RuleCall)cExprAlternatives_2_0.eContents().get(0);
		private final RuleCall cExprAskExpressionParserRuleCall_2_0_1 = (RuleCall)cExprAlternatives_2_0.eContents().get(1);
		private final RuleCall cExprExpressionParserRuleCall_2_0_2 = (RuleCall)cExprAlternatives_2_0.eContents().get(2);
		
		//ModifiedAskStatement sadl::ExpressionScope:
		//	{ModifiedAskStatement} ('Ask' | 'ask') expr=(ConstructExpression | AskExpression | Expression);
		@Override public ParserRule getRule() { return rule; }
		
		//{ModifiedAskStatement} ('Ask' | 'ask') expr=(ConstructExpression | AskExpression | Expression)
		public Group getGroup() { return cGroup; }
		
		//{ModifiedAskStatement}
		public Action getModifiedAskStatementAction_0() { return cModifiedAskStatementAction_0; }
		
		//'Ask' | 'ask'
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'Ask'
		public Keyword getAskKeyword_1_0() { return cAskKeyword_1_0; }
		
		//'ask'
		public Keyword getAskKeyword_1_1() { return cAskKeyword_1_1; }
		
		//expr=(ConstructExpression | AskExpression | Expression)
		public Assignment getExprAssignment_2() { return cExprAssignment_2; }
		
		//(ConstructExpression | AskExpression | Expression)
		public Alternatives getExprAlternatives_2_0() { return cExprAlternatives_2_0; }
		
		//ConstructExpression
		public RuleCall getExprConstructExpressionParserRuleCall_2_0_0() { return cExprConstructExpressionParserRuleCall_2_0_0; }
		
		//AskExpression
		public RuleCall getExprAskExpressionParserRuleCall_2_0_1() { return cExprAskExpressionParserRuleCall_2_0_1; }
		
		//Expression
		public RuleCall getExprExpressionParserRuleCall_2_0_2() { return cExprExpressionParserRuleCall_2_0_2; }
	}
	public class WhatStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ge.research.sadl.darpa.aske.Dialog.WhatStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWhatStatementAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cWhatKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cWhatKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cStmtAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cStmtAlternatives_2_0 = (Alternatives)cStmtAssignment_2.eContents().get(0);
		private final RuleCall cStmtWhatIsStatementParserRuleCall_2_0_0 = (RuleCall)cStmtAlternatives_2_0.eContents().get(0);
		private final RuleCall cStmtWhatValuesStatementParserRuleCall_2_0_1 = (RuleCall)cStmtAlternatives_2_0.eContents().get(1);
		
		//WhatStatement:
		//	{WhatStatement} ('What' | 'what') stmt=(WhatIsStatement | WhatValuesStatement);
		@Override public ParserRule getRule() { return rule; }
		
		//{WhatStatement} ('What' | 'what') stmt=(WhatIsStatement | WhatValuesStatement)
		public Group getGroup() { return cGroup; }
		
		//{WhatStatement}
		public Action getWhatStatementAction_0() { return cWhatStatementAction_0; }
		
		//'What' | 'what'
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'What'
		public Keyword getWhatKeyword_1_0() { return cWhatKeyword_1_0; }
		
		//'what'
		public Keyword getWhatKeyword_1_1() { return cWhatKeyword_1_1; }
		
		//stmt=(WhatIsStatement | WhatValuesStatement)
		public Assignment getStmtAssignment_2() { return cStmtAssignment_2; }
		
		//(WhatIsStatement | WhatValuesStatement)
		public Alternatives getStmtAlternatives_2_0() { return cStmtAlternatives_2_0; }
		
		//WhatIsStatement
		public RuleCall getStmtWhatIsStatementParserRuleCall_2_0_0() { return cStmtWhatIsStatementParserRuleCall_2_0_0; }
		
		//WhatValuesStatement
		public RuleCall getStmtWhatValuesStatementParserRuleCall_2_0_1() { return cStmtWhatValuesStatementParserRuleCall_2_0_1; }
	}
	public class WhatIsStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ge.research.sadl.darpa.aske.Dialog.WhatIsStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWhatIsStatementAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cArticleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cArticleAnArticleParserRuleCall_2_0 = (RuleCall)cArticleAssignment_2.eContents().get(0);
		private final Assignment cTargetAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTargetSadlResourceParserRuleCall_3_0 = (RuleCall)cTargetAssignment_3.eContents().get(0);
		
		//WhatIsStatement:
		//	{WhatIsStatement} 'is' article=AnArticle? target=SadlResource;
		@Override public ParserRule getRule() { return rule; }
		
		//{WhatIsStatement} 'is' article=AnArticle? target=SadlResource
		public Group getGroup() { return cGroup; }
		
		//{WhatIsStatement}
		public Action getWhatIsStatementAction_0() { return cWhatIsStatementAction_0; }
		
		//'is'
		public Keyword getIsKeyword_1() { return cIsKeyword_1; }
		
		//article=AnArticle?
		public Assignment getArticleAssignment_2() { return cArticleAssignment_2; }
		
		//AnArticle
		public RuleCall getArticleAnArticleParserRuleCall_2_0() { return cArticleAnArticleParserRuleCall_2_0; }
		
		//target=SadlResource
		public Assignment getTargetAssignment_3() { return cTargetAssignment_3; }
		
		//SadlResource
		public RuleCall getTargetSadlResourceParserRuleCall_3_0() { return cTargetSadlResourceParserRuleCall_3_0; }
	}
	public class WhatValuesStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ge.research.sadl.darpa.aske.Dialog.WhatValuesStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWhatValuesStatementAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cValueKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cValuesKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cTypAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cTypAlternatives_2_0 = (Alternatives)cTypAssignment_2.eContents().get(0);
		private final Keyword cTypCanKeyword_2_0_0 = (Keyword)cTypAlternatives_2_0.eContents().get(0);
		private final Keyword cTypMustKeyword_2_0_1 = (Keyword)cTypAlternatives_2_0.eContents().get(1);
		private final Assignment cPropAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPropSadlResourceParserRuleCall_3_0 = (RuleCall)cPropAssignment_3.eContents().get(0);
		private final Keyword cOfKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cArticleAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cArticleAnArticleParserRuleCall_5_0 = (RuleCall)cArticleAssignment_5.eContents().get(0);
		private final Assignment cClsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cClsSadlPrimaryTypeReferenceParserRuleCall_6_0 = (RuleCall)cClsAssignment_6.eContents().get(0);
		private final Keyword cHaveKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//WhatValuesStatement:
		//	{WhatValuesStatement} ('value' | 'values') typ=('can' | 'must') prop=SadlResource 'of' article=AnArticle?
		//	cls=SadlPrimaryTypeReference 'have';
		@Override public ParserRule getRule() { return rule; }
		
		//{WhatValuesStatement} ('value' | 'values') typ=('can' | 'must') prop=SadlResource 'of' article=AnArticle?
		//cls=SadlPrimaryTypeReference 'have'
		public Group getGroup() { return cGroup; }
		
		//{WhatValuesStatement}
		public Action getWhatValuesStatementAction_0() { return cWhatValuesStatementAction_0; }
		
		//'value' | 'values'
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'value'
		public Keyword getValueKeyword_1_0() { return cValueKeyword_1_0; }
		
		//'values'
		public Keyword getValuesKeyword_1_1() { return cValuesKeyword_1_1; }
		
		//typ=('can' | 'must')
		public Assignment getTypAssignment_2() { return cTypAssignment_2; }
		
		//('can' | 'must')
		public Alternatives getTypAlternatives_2_0() { return cTypAlternatives_2_0; }
		
		//'can'
		public Keyword getTypCanKeyword_2_0_0() { return cTypCanKeyword_2_0_0; }
		
		//'must'
		public Keyword getTypMustKeyword_2_0_1() { return cTypMustKeyword_2_0_1; }
		
		//prop=SadlResource
		public Assignment getPropAssignment_3() { return cPropAssignment_3; }
		
		//SadlResource
		public RuleCall getPropSadlResourceParserRuleCall_3_0() { return cPropSadlResourceParserRuleCall_3_0; }
		
		//'of'
		public Keyword getOfKeyword_4() { return cOfKeyword_4; }
		
		//article=AnArticle?
		public Assignment getArticleAssignment_5() { return cArticleAssignment_5; }
		
		//AnArticle
		public RuleCall getArticleAnArticleParserRuleCall_5_0() { return cArticleAnArticleParserRuleCall_5_0; }
		
		//cls=SadlPrimaryTypeReference
		public Assignment getClsAssignment_6() { return cClsAssignment_6; }
		
		//SadlPrimaryTypeReference
		public RuleCall getClsSadlPrimaryTypeReferenceParserRuleCall_6_0() { return cClsSadlPrimaryTypeReferenceParserRuleCall_6_0; }
		
		//'have'
		public Keyword getHaveKeyword_7() { return cHaveKeyword_7; }
	}
	public class HowManyValuesStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ge.research.sadl.darpa.aske.Dialog.HowManyValuesStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cHowManyValuesStatementAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cHowKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cHowKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Keyword cManyKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValuesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cOfKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPropAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPropSadlResourceParserRuleCall_5_0 = (RuleCall)cPropAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cOfKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cTypeKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cTypAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cTypSadlPrimaryTypeReferenceParserRuleCall_6_2_0 = (RuleCall)cTypAssignment_6_2.eContents().get(0);
		private final Keyword cCanKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cArticleAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cArticleAnArticleParserRuleCall_8_0 = (RuleCall)cArticleAssignment_8.eContents().get(0);
		private final Assignment cClsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cClsSadlPrimaryTypeReferenceParserRuleCall_9_0 = (RuleCall)cClsAssignment_9.eContents().get(0);
		private final Keyword cHaveKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//HowManyValuesStatement:
		//	{HowManyValuesStatement} ('How' | 'how') 'many' 'values' 'of' prop=SadlResource ('of' 'type'
		//	typ=SadlPrimaryTypeReference)? 'can' article=AnArticle? cls=SadlPrimaryTypeReference 'have';
		@Override public ParserRule getRule() { return rule; }
		
		//{HowManyValuesStatement} ('How' | 'how') 'many' 'values' 'of' prop=SadlResource ('of' 'type'
		//typ=SadlPrimaryTypeReference)? 'can' article=AnArticle? cls=SadlPrimaryTypeReference 'have'
		public Group getGroup() { return cGroup; }
		
		//{HowManyValuesStatement}
		public Action getHowManyValuesStatementAction_0() { return cHowManyValuesStatementAction_0; }
		
		//'How' | 'how'
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'How'
		public Keyword getHowKeyword_1_0() { return cHowKeyword_1_0; }
		
		//'how'
		public Keyword getHowKeyword_1_1() { return cHowKeyword_1_1; }
		
		//'many'
		public Keyword getManyKeyword_2() { return cManyKeyword_2; }
		
		//'values'
		public Keyword getValuesKeyword_3() { return cValuesKeyword_3; }
		
		//'of'
		public Keyword getOfKeyword_4() { return cOfKeyword_4; }
		
		//prop=SadlResource
		public Assignment getPropAssignment_5() { return cPropAssignment_5; }
		
		//SadlResource
		public RuleCall getPropSadlResourceParserRuleCall_5_0() { return cPropSadlResourceParserRuleCall_5_0; }
		
		//('of' 'type' typ=SadlPrimaryTypeReference)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'of'
		public Keyword getOfKeyword_6_0() { return cOfKeyword_6_0; }
		
		//'type'
		public Keyword getTypeKeyword_6_1() { return cTypeKeyword_6_1; }
		
		//typ=SadlPrimaryTypeReference
		public Assignment getTypAssignment_6_2() { return cTypAssignment_6_2; }
		
		//SadlPrimaryTypeReference
		public RuleCall getTypSadlPrimaryTypeReferenceParserRuleCall_6_2_0() { return cTypSadlPrimaryTypeReferenceParserRuleCall_6_2_0; }
		
		//'can'
		public Keyword getCanKeyword_7() { return cCanKeyword_7; }
		
		//article=AnArticle?
		public Assignment getArticleAssignment_8() { return cArticleAssignment_8; }
		
		//AnArticle
		public RuleCall getArticleAnArticleParserRuleCall_8_0() { return cArticleAnArticleParserRuleCall_8_0; }
		
		//cls=SadlPrimaryTypeReference
		public Assignment getClsAssignment_9() { return cClsAssignment_9; }
		
		//SadlPrimaryTypeReference
		public RuleCall getClsSadlPrimaryTypeReferenceParserRuleCall_9_0() { return cClsSadlPrimaryTypeReferenceParserRuleCall_9_0; }
		
		//'have'
		public Keyword getHaveKeyword_10() { return cHaveKeyword_10; }
	}
	public class EOSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.ge.research.sadl.darpa.aske.Dialog.EOS");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEOSParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Keyword cQuestionMarkKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//@Override
		//EOS:
		//	super |
		//	'?';
		@Override public ParserRule getRule() { return rule; }
		
		//super | '?'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//super
		public RuleCall getEOSParserRuleCall_0() { return cEOSParserRuleCall_0; }
		
		//'?'
		public Keyword getQuestionMarkKeyword_1() { return cQuestionMarkKeyword_1; }
	}
	
	
	private final DialogModelElements pDialogModel;
	private final SadlModelElementElements pSadlModelElement;
	private final StringResponseElements pStringResponse;
	private final ModifiedAskStatementElements pModifiedAskStatement;
	private final WhatStatementElements pWhatStatement;
	private final WhatIsStatementElements pWhatIsStatement;
	private final WhatValuesStatementElements pWhatValuesStatement;
	private final HowManyValuesStatementElements pHowManyValuesStatement;
	private final EOSElements pEOS;
	
	private final Grammar grammar;
	
	private final SADLGrammarAccess gaSADL;

	@Inject
	public DialogGrammarAccess(GrammarProvider grammarProvider,
			SADLGrammarAccess gaSADL) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaSADL = gaSADL;
		this.pDialogModel = new DialogModelElements();
		this.pSadlModelElement = new SadlModelElementElements();
		this.pStringResponse = new StringResponseElements();
		this.pModifiedAskStatement = new ModifiedAskStatementElements();
		this.pWhatStatement = new WhatStatementElements();
		this.pWhatIsStatement = new WhatIsStatementElements();
		this.pWhatValuesStatement = new WhatValuesStatementElements();
		this.pHowManyValuesStatement = new HowManyValuesStatementElements();
		this.pEOS = new EOSElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.ge.research.sadl.darpa.aske.Dialog".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public SADLGrammarAccess getSADLGrammarAccess() {
		return gaSADL;
	}

	
	//DialogModel sadl::SadlModel:
	//	super::SadlModel;
	public DialogModelElements getDialogModelAccess() {
		return pDialogModel;
	}
	
	public ParserRule getDialogModelRule() {
		return getDialogModelAccess().getRule();
	}
	
	//@Override
	//SadlModelElement sadl::SadlModelElement:
	//	'CM:' (SadlStatement | EquationStatement | ExternalEquationStatement) EOS |
	//	'CM:' StringResponse EOS | ModifiedAskStatement EOS | WhatStatement EOS | HowManyValuesStatement EOS //|
	//	//	=>CMInput EOS
	//;
	public SadlModelElementElements getSadlModelElementAccess() {
		return pSadlModelElement;
	}
	
	public ParserRule getSadlModelElementRule() {
		return getSadlModelElementAccess().getRule();
	}
	
	//StringResponse:
	//	str=STRING;
	public StringResponseElements getStringResponseAccess() {
		return pStringResponse;
	}
	
	public ParserRule getStringResponseRule() {
		return getStringResponseAccess().getRule();
	}
	
	//ModifiedAskStatement sadl::ExpressionScope:
	//	{ModifiedAskStatement} ('Ask' | 'ask') expr=(ConstructExpression | AskExpression | Expression);
	public ModifiedAskStatementElements getModifiedAskStatementAccess() {
		return pModifiedAskStatement;
	}
	
	public ParserRule getModifiedAskStatementRule() {
		return getModifiedAskStatementAccess().getRule();
	}
	
	//WhatStatement:
	//	{WhatStatement} ('What' | 'what') stmt=(WhatIsStatement | WhatValuesStatement);
	public WhatStatementElements getWhatStatementAccess() {
		return pWhatStatement;
	}
	
	public ParserRule getWhatStatementRule() {
		return getWhatStatementAccess().getRule();
	}
	
	//WhatIsStatement:
	//	{WhatIsStatement} 'is' article=AnArticle? target=SadlResource;
	public WhatIsStatementElements getWhatIsStatementAccess() {
		return pWhatIsStatement;
	}
	
	public ParserRule getWhatIsStatementRule() {
		return getWhatIsStatementAccess().getRule();
	}
	
	//WhatValuesStatement:
	//	{WhatValuesStatement} ('value' | 'values') typ=('can' | 'must') prop=SadlResource 'of' article=AnArticle?
	//	cls=SadlPrimaryTypeReference 'have';
	public WhatValuesStatementElements getWhatValuesStatementAccess() {
		return pWhatValuesStatement;
	}
	
	public ParserRule getWhatValuesStatementRule() {
		return getWhatValuesStatementAccess().getRule();
	}
	
	//HowManyValuesStatement:
	//	{HowManyValuesStatement} ('How' | 'how') 'many' 'values' 'of' prop=SadlResource ('of' 'type'
	//	typ=SadlPrimaryTypeReference)? 'can' article=AnArticle? cls=SadlPrimaryTypeReference 'have';
	public HowManyValuesStatementElements getHowManyValuesStatementAccess() {
		return pHowManyValuesStatement;
	}
	
	public ParserRule getHowManyValuesStatementRule() {
		return getHowManyValuesStatementAccess().getRule();
	}
	
	//@Override
	//EOS:
	//	super |
	//	'?';
	public EOSElements getEOSAccess() {
		return pEOS;
	}
	
	public ParserRule getEOSRule() {
		return getEOSAccess().getRule();
	}
	
	//SadlModel:
	//	'uri' baseUri=STRING ('alias' alias=ID)? ('version' version=STRING)?
	//	annotations+=SadlAnnotation* super::EOS
	//	imports+=SadlImport*
	//	elements+=super::SadlModelElement*;
	public SADLGrammarAccess.SadlModelElements getSadlModelAccess() {
		return gaSADL.getSadlModelAccess();
	}
	
	public ParserRule getSadlModelRule() {
		return getSadlModelAccess().getRule();
	}
	
	//SadlAnnotation:
	//	','? '(' type=('alias' | 'note') contents+=STRING (',' contents+=STRING)* ')';
	public SADLGrammarAccess.SadlAnnotationElements getSadlAnnotationAccess() {
		return gaSADL.getSadlAnnotationAccess();
	}
	
	public ParserRule getSadlAnnotationRule() {
		return getSadlAnnotationAccess().getRule();
	}
	
	//SadlImport:
	//	'import' importedResource=[SadlModel|STRING] ('as' alias=ID)? super::EOS;
	public SADLGrammarAccess.SadlImportElements getSadlImportAccess() {
		return gaSADL.getSadlImportAccess();
	}
	
	public ParserRule getSadlImportRule() {
		return getSadlImportAccess().getRule();
	}
	
	//EquationStatement:
	//	'Equation' EquationSignature
	//	body=Expression? ('return' retval=Expression)? ('where' where=Expression)?;
	public SADLGrammarAccess.EquationStatementElements getEquationStatementAccess() {
		return gaSADL.getEquationStatementAccess();
	}
	
	public ParserRule getEquationStatementRule() {
		return getEquationStatementAccess().getRule();
	}
	
	//ExternalEquationStatement:
	//	'External' EquationSignature
	//	uri=STRING ('located' 'at' location=STRING)? ('where' where=Expression)?;
	public SADLGrammarAccess.ExternalEquationStatementElements getExternalEquationStatementAccess() {
		return gaSADL.getExternalEquationStatementAccess();
	}
	
	public ParserRule getExternalEquationStatementRule() {
		return getExternalEquationStatementAccess().getRule();
	}
	
	//fragment EquationSignature returns AbstractSadlEquation:
	//	name=SadlResource '(' (parameter+=SadlParameterDeclaration (',' parameter+=SadlParameterDeclaration)*)? ')' 'returns'
	//	(returnType+=SadlReturnDeclaration (',' returnType+=SadlReturnDeclaration)*) ':';
	public SADLGrammarAccess.EquationSignatureElements getEquationSignatureAccess() {
		return gaSADL.getEquationSignatureAccess();
	}
	
	public ParserRule getEquationSignatureRule() {
		return getEquationSignatureAccess().getRule();
	}
	
	//SadlParameterDeclaration:
	//	type=SadlPrimaryTypeReference name=SadlResource
	//	| unknown='--'
	//	| ellipsis='...';
	public SADLGrammarAccess.SadlParameterDeclarationElements getSadlParameterDeclarationAccess() {
		return gaSADL.getSadlParameterDeclarationAccess();
	}
	
	public ParserRule getSadlParameterDeclarationRule() {
		return getSadlParameterDeclarationAccess().getRule();
	}
	
	//SadlReturnDeclaration:
	//	type=SadlPrimaryTypeReference
	//	| none='None'
	//	| unknown='--';
	public SADLGrammarAccess.SadlReturnDeclarationElements getSadlReturnDeclarationAccess() {
		return gaSADL.getSadlReturnDeclarationAccess();
	}
	
	public ParserRule getSadlReturnDeclarationRule() {
		return getSadlReturnDeclarationAccess().getRule();
	}
	
	//// These are the things that translate directly to OWL.
	//SadlStatement:
	//	SadlResource ({SadlClassOrPropertyDeclaration.classOrProperty+=current} 'is' 'a' ('top-level'? 'class'
	//	| 'type' 'of' superElement=SadlPrimaryTypeReference facet=SadlDataTypeFacet?)
	//	(describedBy+=SadlPropertyDeclarationInClass+ | (','? restrictions+=SadlPropertyRestriction)+)?
	//	| {SadlProperty.nameOrRef=current} primaryDeclaration?='is' 'a' 'property' (','?
	//	restrictions+=SadlPropertyRestriction)*
	//	| {SadlProperty.nameOrRef=current} (','? restrictions+=SadlPropertyRestriction)+
	//	| {SadlSameAs.nameOrRef=current} 'is' 'the' 'same' 'as' complement?='not'? sameAs=SadlTypeReference
	//	| {SadlDifferentFrom.nameOrRef=current} 'is' 'not' 'the' 'same' 'as' notTheSameAs=SadlTypeReference
	//	| {SadlInstance.nameOrRef=current} ('is' AnArticle type=SadlTypeReference)? (listInitializer=SadlValueList |
	//	propertyInitializers+=SadlPropertyInitializer+)?
	//	| {SadlDisjointClasses.classes+=current} ('and' classes+=SadlResource)+ 'are' 'disjoint') |
	//	{SadlClassOrPropertyDeclaration} '{' classOrProperty+=SadlResource (',' classOrProperty+=SadlResource)* '}' 'are'
	//	(('top-level'? 'classes' | (oftype='types' | oftype='instances') 'of' superElement=SadlPrimaryTypeReference)
	//	describedBy+=SadlPropertyDeclarationInClass*
	//	| {SadlDisjointClasses.types+=current} 'disjoint'
	//	| {SadlDifferentFrom.types+=current} complement?='not'? 'the' 'same') | {SadlProperty} AnArticle? 'relationship' 'of'
	//	from=SadlTypeReference 'to' to=SadlTypeReference 'is' property=SadlResource
	//	| AnArticle SadlTypeReference ({SadlInstance.type=current} instance=SadlResource?
	//	propertyInitializers+=SadlPropertyInitializer*
	//	| {SadlNecessaryAndSufficient.subject=current} 'is' AnArticle object=SadlResource 'only' 'if'
	//	propConditions+=SadlPropertyCondition ('and' propConditions+=SadlPropertyCondition)*);
	public SADLGrammarAccess.SadlStatementElements getSadlStatementAccess() {
		return gaSADL.getSadlStatementAccess();
	}
	
	public ParserRule getSadlStatementRule() {
		return getSadlStatementAccess().getRule();
	}
	
	//SadlPropertyCondition:
	//	property=[SadlResource|QNAME] cond+=SadlCondition;
	public SADLGrammarAccess.SadlPropertyConditionElements getSadlPropertyConditionAccess() {
		return gaSADL.getSadlPropertyConditionAccess();
	}
	
	public ParserRule getSadlPropertyConditionRule() {
		return getSadlPropertyConditionAccess().getRule();
	}
	
	//SadlPropertyInitializer:
	//	','? ('with' | 'has')? property=[SadlResource|QNAME] (value=SadlExplicitValue | '(' value=SadlNestedInstance ')') |
	//	','? 'is' property=[SadlResource|QNAME] 'of' type=[SadlResource|QNAME] | ','? 'of' property=[SadlResource|QNAME] 'is'
	//	(value=SadlExplicitValue | '(' value=SadlNestedInstance ')');
	public SADLGrammarAccess.SadlPropertyInitializerElements getSadlPropertyInitializerAccess() {
		return gaSADL.getSadlPropertyInitializerAccess();
	}
	
	public ParserRule getSadlPropertyInitializerRule() {
		return getSadlPropertyInitializerAccess().getRule();
	}
	
	//SadlNestedInstance SadlInstance:
	//	{SadlNestedInstance} (instance=SadlResource 'is' article=AnArticle type=SadlTypeReference
	//	propertyInitializers+=SadlPropertyInitializer*
	//	| article=AnArticle type=SadlTypeReference instance=SadlResource? propertyInitializers+=SadlPropertyInitializer*);
	public SADLGrammarAccess.SadlNestedInstanceElements getSadlNestedInstanceAccess() {
		return gaSADL.getSadlNestedInstanceAccess();
	}
	
	public ParserRule getSadlNestedInstanceRule() {
		return getSadlNestedInstanceAccess().getRule();
	}
	
	//SadlResource:
	//	name=[SadlResource|QNAME] annotations+=SadlAnnotation*;
	public SADLGrammarAccess.SadlResourceElements getSadlResourceAccess() {
		return gaSADL.getSadlResourceAccess();
	}
	
	public ParserRule getSadlResourceRule() {
		return getSadlResourceAccess().getRule();
	}
	
	//SadlDataTypeFacet:
	//	{SadlDataTypeFacet} ('(' | minInclusive?='[') min=FacetNumber? ',' max=FacetNumber? (maxInclusive?=']' | ')') |
	//	regex=STRING
	//	| 'length' (len=FacetNumber | minlen=FacetNumber '-' maxlen=(FacetNumber | '*')) | '{' values+=FacetValue (','?
	//	values+=FacetValue)* '}';
	public SADLGrammarAccess.SadlDataTypeFacetElements getSadlDataTypeFacetAccess() {
		return gaSADL.getSadlDataTypeFacetAccess();
	}
	
	public ParserRule getSadlDataTypeFacetRule() {
		return getSadlDataTypeFacetAccess().getRule();
	}
	
	//FacetNumber:
	//	'-'? AnyNumber;
	public SADLGrammarAccess.FacetNumberElements getFacetNumberAccess() {
		return gaSADL.getFacetNumberAccess();
	}
	
	public ParserRule getFacetNumberRule() {
		return getFacetNumberAccess().getRule();
	}
	
	//FacetValue:
	//	STRING | FacetNumber;
	public SADLGrammarAccess.FacetValueElements getFacetValueAccess() {
		return gaSADL.getFacetValueAccess();
	}
	
	public ParserRule getFacetValueRule() {
		return getFacetValueAccess().getRule();
	}
	
	//// TypeReferences
	//SadlTypeReference:
	//	SadlUnionType;
	public SADLGrammarAccess.SadlTypeReferenceElements getSadlTypeReferenceAccess() {
		return gaSADL.getSadlTypeReferenceAccess();
	}
	
	public ParserRule getSadlTypeReferenceRule() {
		return getSadlTypeReferenceAccess().getRule();
	}
	
	//SadlUnionType SadlTypeReference:
	//	SadlIntersectionType ({SadlUnionType.left=current} 'or' right=SadlIntersectionType)*;
	public SADLGrammarAccess.SadlUnionTypeElements getSadlUnionTypeAccess() {
		return gaSADL.getSadlUnionTypeAccess();
	}
	
	public ParserRule getSadlUnionTypeRule() {
		return getSadlUnionTypeAccess().getRule();
	}
	
	//SadlIntersectionType SadlTypeReference:
	//	SadlPrimaryTypeReference ({SadlIntersectionType.left=current} 'and' right=SadlPrimaryTypeReference)*;
	public SADLGrammarAccess.SadlIntersectionTypeElements getSadlIntersectionTypeAccess() {
		return gaSADL.getSadlIntersectionTypeAccess();
	}
	
	public ParserRule getSadlIntersectionTypeRule() {
		return getSadlIntersectionTypeAccess().getRule();
	}
	
	//SadlPrimaryTypeReference SadlTypeReference:
	//	{SadlSimpleTypeReference} type=[SadlResource|QNAME] list?='List'?
	//	| {SadlPrimitiveDataType} primitiveType=SadlDataType list?='List'?
	//	| '(' SadlPropertyCondition ')'
	//	| '{' SadlTypeReference '}';
	public SADLGrammarAccess.SadlPrimaryTypeReferenceElements getSadlPrimaryTypeReferenceAccess() {
		return gaSADL.getSadlPrimaryTypeReferenceAccess();
	}
	
	public ParserRule getSadlPrimaryTypeReferenceRule() {
		return getSadlPrimaryTypeReferenceAccess().getRule();
	}
	
	//enum SadlDataType:
	//	string | boolean | decimal | int | long | float | double | duration | dateTime | time | date |
	//	gYearMonth | gYear | gMonthDay | gDay | gMonth | hexBinary | base64Binary | anyURI |
	//	integer | negativeInteger | nonNegativeInteger | positiveInteger | nonPositiveInteger |
	//	byte | unsignedByte | unsignedInt | anySimpleType;
	public SADLGrammarAccess.SadlDataTypeElements getSadlDataTypeAccess() {
		return gaSADL.getSadlDataTypeAccess();
	}
	
	public EnumRule getSadlDataTypeRule() {
		return getSadlDataTypeAccess().getRule();
	}
	
	//// Class declarations may also describe the class's properties.
	//SadlPropertyDeclarationInClass SadlProperty:
	//	','? 'described' 'by' nameDeclarations+=SadlResource restrictions+=SadlPropertyRestriction*;
	public SADLGrammarAccess.SadlPropertyDeclarationInClassElements getSadlPropertyDeclarationInClassAccess() {
		return gaSADL.getSadlPropertyDeclarationInClassAccess();
	}
	
	public ParserRule getSadlPropertyDeclarationInClassRule() {
		return getSadlPropertyDeclarationInClassAccess().getRule();
	}
	
	//SadlPropertyRestriction:
	//	SadlCondition
	//	| {SadlTypeAssociation} ('describes' | 'of') domain=SadlTypeReference
	//	| {SadlRangeRestriction} ('has' | 'with') ('a' singleValued?='single' 'value' | 'values') 'of' 'type'
	//	(typeonly=('class' | 'data') | range=SadlPrimaryTypeReference facet=SadlDataTypeFacet?) | {SadlIsInverseOf} 'is'
	//	'the' 'inverse' 'of' otherProperty=[SadlResource|QNAME] | {SadlIsTransitive} 'is' 'transitive'
	//	| {SadlIsSymmetrical} 'is' 'symmetrical'
	//	| {SadlIsAnnotation} 'is' 'a' 'type' 'of' 'annotation'
	//	| {SadlDefaultValue} 'has' ('level' level=NUMBER)? 'default' defValue=SadlExplicitValue
	//	| {SadlIsFunctional} 'has' 'a' 'single' (inverse?='subject' | 'value')?
	//	| {SadlMustBeOneOf} 'must' 'be' 'one' 'of' '{' values+=SadlExplicitValue (',' values+=SadlExplicitValue)* '}'
	//	| {SadlCanOnlyBeOneOf} 'can' 'only' 'be' 'one' 'of' '{' values+=SadlExplicitValue (',' values+=SadlExplicitValue)*
	//	'}';
	public SADLGrammarAccess.SadlPropertyRestrictionElements getSadlPropertyRestrictionAccess() {
		return gaSADL.getSadlPropertyRestrictionAccess();
	}
	
	public ParserRule getSadlPropertyRestrictionRule() {
		return getSadlPropertyRestrictionAccess().getRule();
	}
	
	//SadlCondition:
	//	SadlAllValuesCondition
	//	| SadlHasValueCondition
	//	| SadlCardinalityCondition;
	public SADLGrammarAccess.SadlConditionElements getSadlConditionAccess() {
		return gaSADL.getSadlConditionAccess();
	}
	
	public ParserRule getSadlConditionRule() {
		return getSadlConditionAccess().getRule();
	}
	
	//SadlAllValuesCondition:
	//	'only' ('has' | 'with') 'values' 'of' 'type' type=SadlPrimaryTypeReference facet=SadlDataTypeFacet?;
	public SADLGrammarAccess.SadlAllValuesConditionElements getSadlAllValuesConditionAccess() {
		return gaSADL.getSadlAllValuesConditionAccess();
	}
	
	public ParserRule getSadlAllValuesConditionRule() {
		return getSadlAllValuesConditionAccess().getRule();
	}
	
	//SadlHasValueCondition:
	//	'always' ('has' | 'with') 'value' (restriction=SadlExplicitValue | '(' restriction=SadlNestedInstance ')');
	public SADLGrammarAccess.SadlHasValueConditionElements getSadlHasValueConditionAccess() {
		return gaSADL.getSadlHasValueConditionAccess();
	}
	
	public ParserRule getSadlHasValueConditionRule() {
		return getSadlHasValueConditionAccess().getRule();
	}
	
	//SadlCardinalityCondition:
	//	('has' | 'with') ('at' operator=('least' | 'most') | 'exactly')?
	//	cardinality=CardinalityValue ('value' | 'values') ('of' 'type' type=SadlPrimaryTypeReference
	//	facet=SadlDataTypeFacet?)?;
	public SADLGrammarAccess.SadlCardinalityConditionElements getSadlCardinalityConditionAccess() {
		return gaSADL.getSadlCardinalityConditionAccess();
	}
	
	public ParserRule getSadlCardinalityConditionRule() {
		return getSadlCardinalityConditionAccess().getRule();
	}
	
	//CardinalityValue:
	//	NUMBER | 'one';
	public SADLGrammarAccess.CardinalityValueElements getCardinalityValueAccess() {
		return gaSADL.getCardinalityValueAccess();
	}
	
	public ParserRule getCardinalityValueRule() {
		return getCardinalityValueAccess().getRule();
	}
	
	//SadlExplicitValue:
	//	SadlExplicitValueLiteral |
	//	=> ({SadlUnaryExpression} operator=('-' | 'not') value=SadlExplicitValueLiteral);
	public SADLGrammarAccess.SadlExplicitValueElements getSadlExplicitValueAccess() {
		return gaSADL.getSadlExplicitValueAccess();
	}
	
	public ParserRule getSadlExplicitValueRule() {
		return getSadlExplicitValueAccess().getRule();
	}
	
	//SadlExplicitValueLiteral:
	//	SadlResource // e.g., George
	//	| {SadlNumberLiteral} literalNumber=AnyNumber -> unit=UNIT?
	//	| {SadlStringLiteral} literalString=STRING
	//	| {SadlBooleanLiteral} (truethy?='true' | 'false') | SadlValueList
	//	| {SadlConstantLiteral} term=('PI' | 'e' | 'known');
	public SADLGrammarAccess.SadlExplicitValueLiteralElements getSadlExplicitValueLiteralAccess() {
		return gaSADL.getSadlExplicitValueLiteralAccess();
	}
	
	public ParserRule getSadlExplicitValueLiteralRule() {
		return getSadlExplicitValueLiteralAccess().getRule();
	}
	
	//UNIT:
	//	STRING | ID;
	public SADLGrammarAccess.UNITElements getUNITAccess() {
		return gaSADL.getUNITAccess();
	}
	
	public ParserRule getUNITRule() {
		return getUNITAccess().getRule();
	}
	
	//SadlValueList:
	//	{SadlValueList} '[' (explicitValues+=SadlExplicitValue (',' explicitValues+=SadlExplicitValue)*)? ']';
	public SADLGrammarAccess.SadlValueListElements getSadlValueListAccess() {
		return gaSADL.getSadlValueListAccess();
	}
	
	public ParserRule getSadlValueListRule() {
		return getSadlValueListAccess().getRule();
	}
	
	//// These articles can appear before the property name and are indicative of the functionality of the property or
	////	the cardinality of the property on the class
	//AnArticle:
	//	IndefiniteArticle | DefiniteArticle;
	public SADLGrammarAccess.AnArticleElements getAnArticleAccess() {
		return gaSADL.getAnArticleAccess();
	}
	
	public ParserRule getAnArticleRule() {
		return getAnArticleAccess().getRule();
	}
	
	//IndefiniteArticle:
	//	'A' | 'a' | 'An' | 'an' | 'any' | 'some' | 'another';
	public SADLGrammarAccess.IndefiniteArticleElements getIndefiniteArticleAccess() {
		return gaSADL.getIndefiniteArticleAccess();
	}
	
	public ParserRule getIndefiniteArticleRule() {
		return getIndefiniteArticleAccess().getRule();
	}
	
	//DefiniteArticle:
	//	'The' | 'the';
	public SADLGrammarAccess.DefiniteArticleElements getDefiniteArticleAccess() {
		return gaSADL.getDefiniteArticleAccess();
	}
	
	public ParserRule getDefiniteArticleRule() {
		return getDefiniteArticleAccess().getRule();
	}
	
	//Ordinal:
	//	'first'
	//	| 'second' | 'other'
	//	| 'third'
	//	| 'fourth'
	//	| 'fifth'
	//	| 'sixth'
	//	| 'seventh'
	//	| 'eighth'
	//	| 'ninth'
	//	| 'tenth';
	public SADLGrammarAccess.OrdinalElements getOrdinalAccess() {
		return gaSADL.getOrdinalAccess();
	}
	
	public ParserRule getOrdinalRule() {
		return getOrdinalAccess().getRule();
	}
	
	//// This is primarily for debugging purposes. Any expression can be given after "Expr:" to see if it is valid. 
	//// Such an expression has no meaning in translation.
	//ExpressionStatement ExpressionScope:
	//	{ExpressionStatement}
	//	'Expr:' expr=Expression ('=>' evaluatesTo=STRING)?;
	public SADLGrammarAccess.ExpressionStatementElements getExpressionStatementAccess() {
		return gaSADL.getExpressionStatementAccess();
	}
	
	public ParserRule getExpressionStatementRule() {
		return getExpressionStatementAccess().getRule();
	}
	
	//NamedStructureAnnotation:
	//	','? '(' type=SadlResource contents+=SadlExplicitValue (',' contents+=SadlExplicitValue)* ')';
	public SADLGrammarAccess.NamedStructureAnnotationElements getNamedStructureAnnotationAccess() {
		return gaSADL.getNamedStructureAnnotationAccess();
	}
	
	public ParserRule getNamedStructureAnnotationRule() {
		return getNamedStructureAnnotationAccess().getRule();
	}
	
	//RuleStatement ExpressionScope:
	//	{RuleStatement} ('Stage' stage=NUMBER)? 'Rule' name=SadlResource annotations+=NamedStructureAnnotation* ':'? ('given'
	//	ifs+=Expression)? ('if' ifs+=Expression)? // (','? ifs+=Expression)*
	//	'then' thens+=Expression // (','? thens+=Expression)*
	//;
	public SADLGrammarAccess.RuleStatementElements getRuleStatementAccess() {
		return gaSADL.getRuleStatementAccess();
	}
	
	public ParserRule getRuleStatementRule() {
		return getRuleStatementAccess().getRule();
	}
	
	//QueryStatement ExpressionScope:
	//	{QueryStatement} start=('Ask' | 'Graph') ((name=SadlResource annotations+=NamedStructureAnnotation*)? ':'
	//	expr=(ConstructExpression | AskExpression | Expression) | name=SadlResource);
	public SADLGrammarAccess.QueryStatementElements getQueryStatementAccess() {
		return gaSADL.getQueryStatementAccess();
	}
	
	public ParserRule getQueryStatementRule() {
		return getQueryStatementAccess().getRule();
	}
	
	//UpdateStatement ExpressionScope:
	//	{UpdateStatement}
	//	'Update' ((name=SadlResource annotations+=NamedStructureAnnotation*)? ':' expr=(UpdateExpression | Expression) |
	//	name=SadlResource);
	public SADLGrammarAccess.UpdateStatementElements getUpdateStatementAccess() {
		return gaSADL.getUpdateStatementAccess();
	}
	
	public ParserRule getUpdateStatementRule() {
		return getUpdateStatementAccess().getRule();
	}
	
	//ConstructExpression Expression:
	//	{ConstructExpression}
	//	'construct' subj=SadlResource ','? pred=SadlResource ','? obj=SadlResource 'where' whereExpression=Expression;
	public SADLGrammarAccess.ConstructExpressionElements getConstructExpressionAccess() {
		return gaSADL.getConstructExpressionAccess();
	}
	
	public ParserRule getConstructExpressionRule() {
		return getConstructExpressionAccess().getRule();
	}
	
	//AskExpression Expression:
	//	{AskExpression}
	//	'ask' 'where' whereExpression=Expression;
	public SADLGrammarAccess.AskExpressionElements getAskExpressionAccess() {
		return gaSADL.getAskExpressionAccess();
	}
	
	public ParserRule getAskExpressionRule() {
		return getAskExpressionAccess().getRule();
	}
	
	//UpdateExpression Expression:
	//	{UpdateExpression} ('delete' dData='data'? deleteExpression=Expression)? ('insert' iData='data'?
	//	insertExpression=Expression)? ('where' whereExpression=Expression)?;
	public SADLGrammarAccess.UpdateExpressionElements getUpdateExpressionAccess() {
		return gaSADL.getUpdateExpressionAccess();
	}
	
	public ParserRule getUpdateExpressionRule() {
		return getUpdateExpressionAccess().getRule();
	}
	
	//TestStatement ExpressionScope:
	//	{TestStatement}
	//	'Test:' tests+=Expression;
	public SADLGrammarAccess.TestStatementElements getTestStatementAccess() {
		return gaSADL.getTestStatementAccess();
	}
	
	public ParserRule getTestStatementRule() {
		return getTestStatementAccess().getRule();
	}
	
	//PrintStatement:
	//	'Print:' (displayString=STRING
	//	| model='Deductions'
	//	| model='Model');
	public SADLGrammarAccess.PrintStatementElements getPrintStatementAccess() {
		return gaSADL.getPrintStatementAccess();
	}
	
	public ParserRule getPrintStatementRule() {
		return getPrintStatementAccess().getRule();
	}
	
	//ExplainStatement:
	//	'Explain:' (expr=Expression
	//	| 'Rule' rulename=SadlResource);
	public SADLGrammarAccess.ExplainStatementElements getExplainStatementAccess() {
		return gaSADL.getExplainStatementAccess();
	}
	
	public ParserRule getExplainStatementRule() {
		return getExplainStatementAccess().getRule();
	}
	
	//StartWriteStatement:
	//	write='Write:' dataOnly='data'? '{';
	public SADLGrammarAccess.StartWriteStatementElements getStartWriteStatementAccess() {
		return gaSADL.getStartWriteStatementAccess();
	}
	
	public ParserRule getStartWriteStatementRule() {
		return getStartWriteStatementAccess().getRule();
	}
	
	//EndWriteStatement:
	//	'}' 'to' filename=STRING;
	public SADLGrammarAccess.EndWriteStatementElements getEndWriteStatementAccess() {
		return gaSADL.getEndWriteStatementAccess();
	}
	
	public ParserRule getEndWriteStatementRule() {
		return getEndWriteStatementAccess().getRule();
	}
	
	//ReadStatement:
	//	'Read:' 'data' 'from' filename=STRING ('using' templateFilename=STRING)?;
	public SADLGrammarAccess.ReadStatementElements getReadStatementAccess() {
		return gaSADL.getReadStatementAccess();
	}
	
	public ParserRule getReadStatementRule() {
		return getReadStatementAccess().getRule();
	}
	
	//Expression:
	//	SelectExpression<true,true>;
	public SADLGrammarAccess.ExpressionElements getExpressionAccess() {
		return gaSADL.getExpressionAccess();
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//NestedExpression Expression:
	//	SelectExpression<true,false>;
	public SADLGrammarAccess.NestedExpressionElements getNestedExpressionAccess() {
		return gaSADL.getNestedExpressionAccess();
	}
	
	public ParserRule getNestedExpressionRule() {
		return getNestedExpressionAccess().getRule();
	}
	
	//SelectExpression <EnabledWith, EnableComma Expression:
	//	-> ({SelectExpression}
	//	'select' distinct?='distinct'? ('*' | selectFrom+=SadlResource (','? selectFrom+=SadlResource)*) 'where'
	//	whereExpression=ExpressionParameterized<EnabledWith,EnableComma> (orderby='order' 'by' orderList+=OrderElement ->
	//	(','? orderList+=OrderElement)*)?) | ExpressionParameterized<EnabledWith,EnableComma>;
	public SADLGrammarAccess.SelectExpressionElements getSelectExpressionAccess() {
		return gaSADL.getSelectExpressionAccess();
	}
	
	public ParserRule getSelectExpressionRule() {
		return getSelectExpressionAccess().getRule();
	}
	
	//OrderElement:
	//	('asc' | desc?='desc')? orderBy=SadlResource;
	public SADLGrammarAccess.OrderElementElements getOrderElementAccess() {
		return gaSADL.getOrderElementAccess();
	}
	
	public ParserRule getOrderElementRule() {
		return getOrderElementAccess().getRule();
	}
	
	//// Real expressions start here
	//ExpressionParameterized <EnabledWith, EnableComma Expression:
	//	{Sublist} AnArticle? 'sublist' 'of' list=OrExpression<EnabledWith,EnableComma> 'matching'
	//	where=OrExpression<EnabledWith,EnableComma> | OrExpression<EnabledWith,EnableComma>;
	public SADLGrammarAccess.ExpressionParameterizedElements getExpressionParameterizedAccess() {
		return gaSADL.getExpressionParameterizedAccess();
	}
	
	public ParserRule getExpressionParameterizedRule() {
		return getExpressionParameterizedAccess().getRule();
	}
	
	//OrExpression <EnabledWith, EnableComma Expression:
	//	AndExpression<EnabledWith,EnableComma> ({BinaryOperation.left=current} op=OpOr
	//	right=AndExpression<EnabledWith,EnableComma>)*;
	public SADLGrammarAccess.OrExpressionElements getOrExpressionAccess() {
		return gaSADL.getOrExpressionAccess();
	}
	
	public ParserRule getOrExpressionRule() {
		return getOrExpressionAccess().getRule();
	}
	
	//OpOr:
	//	'or' | '||';
	public SADLGrammarAccess.OpOrElements getOpOrAccess() {
		return gaSADL.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}
	
	//AndExpression <EnabledWith, EnableComma Expression:
	//	EqualityExpression<EnabledWith,EnableComma> ({BinaryOperation.left=current} op=OpAnd
	//	right=EqualityExpression<EnabledWith,EnableComma>)*;
	public SADLGrammarAccess.AndExpressionElements getAndExpressionAccess() {
		return gaSADL.getAndExpressionAccess();
	}
	
	public ParserRule getAndExpressionRule() {
		return getAndExpressionAccess().getRule();
	}
	
	//OpAnd:
	//	'and' | '&&';
	public SADLGrammarAccess.OpAndElements getOpAndAccess() {
		return gaSADL.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}
	
	//EqualityExpression <EnabledWith, EnableComma Expression:
	//	RelationalExpression<EnabledWith,EnableComma> ({BinaryOperation.left=current} op=InfixOperator
	//	right=RelationalExpression<EnabledWith,EnableComma>)*;
	public SADLGrammarAccess.EqualityExpressionElements getEqualityExpressionAccess() {
		return gaSADL.getEqualityExpressionAccess();
	}
	
	public ParserRule getEqualityExpressionRule() {
		return getEqualityExpressionAccess().getRule();
	}
	
	//InfixOperator:
	//	'=='
	//	| '!='
	//	| '='
	//	| 'is' ('not'? 'unique' 'in')?
	//	| 'contains'
	//	| 'does' 'not' 'contain';
	public SADLGrammarAccess.InfixOperatorElements getInfixOperatorAccess() {
		return gaSADL.getInfixOperatorAccess();
	}
	
	public ParserRule getInfixOperatorRule() {
		return getInfixOperatorAccess().getRule();
	}
	
	//RelationalExpression <EnabledWith, EnableComma Expression:
	//	Addition<EnabledWith,EnableComma> -> ({BinaryOperation.left=current} => op=OpCompare
	//	right=Addition<EnabledWith,EnableComma>)*;
	public SADLGrammarAccess.RelationalExpressionElements getRelationalExpressionAccess() {
		return gaSADL.getRelationalExpressionAccess();
	}
	
	public ParserRule getRelationalExpressionRule() {
		return getRelationalExpressionAccess().getRule();
	}
	
	//OpCompare:
	//	'>=' | '<=' | '>' | '<';
	public SADLGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaSADL.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}
	
	//Addition <EnabledWith, EnableComma Expression:
	//	Multiplication<EnabledWith,EnableComma> ({BinaryOperation.left=current} op=AddOp
	//	right=Multiplication<EnabledWith,EnableComma>)*;
	public SADLGrammarAccess.AdditionElements getAdditionAccess() {
		return gaSADL.getAdditionAccess();
	}
	
	public ParserRule getAdditionRule() {
		return getAdditionAccess().getRule();
	}
	
	//AddOp:
	//	'+' | '-';
	public SADLGrammarAccess.AddOpElements getAddOpAccess() {
		return gaSADL.getAddOpAccess();
	}
	
	public ParserRule getAddOpRule() {
		return getAddOpAccess().getRule();
	}
	
	//Multiplication <EnabledWith, EnableComma Expression:
	//	Power<EnabledWith,EnableComma> ({BinaryOperation.left=current} op=MultiOp right=Power<EnabledWith,EnableComma>)*;
	public SADLGrammarAccess.MultiplicationElements getMultiplicationAccess() {
		return gaSADL.getMultiplicationAccess();
	}
	
	public ParserRule getMultiplicationRule() {
		return getMultiplicationAccess().getRule();
	}
	
	//MultiOp:
	//	'*' | '/' | '%';
	public SADLGrammarAccess.MultiOpElements getMultiOpAccess() {
		return gaSADL.getMultiOpAccess();
	}
	
	public ParserRule getMultiOpRule() {
		return getMultiOpAccess().getRule();
	}
	
	//Power <EnabledWith, EnableComma Expression:
	//	PropOfSubject<EnabledWith,EnableComma> ({BinaryOperation.left=current} op='^'
	//	right=PropOfSubject<EnabledWith,EnableComma>)*;
	public SADLGrammarAccess.PowerElements getPowerAccess() {
		return gaSADL.getPowerAccess();
	}
	
	public ParserRule getPowerRule() {
		return getPowerAccess().getRule();
	}
	
	//PropOfSubject <EnabledWith, EnableComma Expression:
	//	ElementInList<EnabledWith,EnableComma> -> ({PropOfSubject.left=current} of=('of' | 'for' | 'in')
	//	right=PropOfSubject<EnabledWith,EnableComma> | -> ({SubjHasProp.left=current} (<EnableComma> comma?=',')?
	//	(<EnabledWith> 'with' | 'has')? prop=SadlResource -> right=ElementInList<EnabledWith,EnableComma>?)+)?;
	public SADLGrammarAccess.PropOfSubjectElements getPropOfSubjectAccess() {
		return gaSADL.getPropOfSubjectAccess();
	}
	
	public ParserRule getPropOfSubjectRule() {
		return getPropOfSubjectAccess().getRule();
	}
	
	//ElementInList <EnabledWith, EnableComma Expression:
	//	UnitExpression<EnabledWith,EnableComma> | {ElementInList} 'element' (before?='before' | after?='after')?
	//	element=UnitExpression<EnabledWith,EnableComma>;
	public SADLGrammarAccess.ElementInListElements getElementInListAccess() {
		return gaSADL.getElementInListAccess();
	}
	
	public ParserRule getElementInListRule() {
		return getElementInListAccess().getRule();
	}
	
	//UnitExpression <EnabledWith, EnableComma Expression:
	//	UnaryExpression<EnabledWith,EnableComma> ({UnitExpression.left=current} unit=STRING)?;
	public SADLGrammarAccess.UnitExpressionElements getUnitExpressionAccess() {
		return gaSADL.getUnitExpressionAccess();
	}
	
	public ParserRule getUnitExpressionRule() {
		return getUnitExpressionAccess().getRule();
	}
	
	//UnaryExpression <EnabledWith, EnableComma Expression:
	//	PrimaryExpression<EnabledWith,EnableComma> | {UnaryExpression} op=('not' | '!' | 'only' | '-' | ThereExists)
	//	expr=PrimaryExpression<EnabledWith,EnableComma>;
	public SADLGrammarAccess.UnaryExpressionElements getUnaryExpressionAccess() {
		return gaSADL.getUnaryExpressionAccess();
	}
	
	public ParserRule getUnaryExpressionRule() {
		return getUnaryExpressionAccess().getRule();
	}
	
	//ThereExists:
	//	'there' 'exists';
	public SADLGrammarAccess.ThereExistsElements getThereExistsAccess() {
		return gaSADL.getThereExistsAccess();
	}
	
	public ParserRule getThereExistsRule() {
		return getThereExistsAccess().getRule();
	}
	
	//// primary expressions are the atom units of expression in the grammar	
	//PrimaryExpression <EnabledWith, EnableComma Expression:
	//	'(' SelectExpression<EnabledWith,EnableComma> ')'
	//	| Name
	//	| {Declaration} article=AnArticle ordinal=Ordinal? type=SadlPrimaryTypeReference ('[' arglist+=NestedExpression? (','
	//	arglist+=NestedExpression)* ']'
	//	| 'length' len=FacetNumber -> ('-' maxlen=(FacetNumber | '*'))?)?
	//	| {StringLiteral} value=STRING
	//	| {NumberLiteral} value=AnyNumber
	//	| {BooleanLiteral} value=BooleanValue
	//	| {Constant} constant=Constants
	//	| {ValueTable} valueTable=ValueTable;
	public SADLGrammarAccess.PrimaryExpressionElements getPrimaryExpressionAccess() {
		return gaSADL.getPrimaryExpressionAccess();
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}
	
	//Name SadlResource:
	//	{Name} name=[SadlResource|QNAME] -> (function?='(' arglist+=NestedExpression? (',' arglist+=NestedExpression)* ')')?;
	public SADLGrammarAccess.NameElements getNameAccess() {
		return gaSADL.getNameAccess();
	}
	
	public ParserRule getNameRule() {
		return getNameAccess().getRule();
	}
	
	//// the truth table
	//ValueTable:
	//	'[' row=ValueRow ']'
	//	// e.g., [George, 23, "Purple", 38.186111]
	//	| '{' '[' rows+=ValueRow ']' (','? '[' rows+=ValueRow ']')* '}'
	//	// e.g., {[George, 23, "Purple", 38.186111], [Martha, 24, "Pink", 45.203]}
	//;
	public SADLGrammarAccess.ValueTableElements getValueTableAccess() {
		return gaSADL.getValueTableAccess();
	}
	
	public ParserRule getValueTableRule() {
		return getValueTableAccess().getRule();
	}
	
	//BooleanValue:
	//	'true' | 'false';
	public SADLGrammarAccess.BooleanValueElements getBooleanValueAccess() {
		return gaSADL.getBooleanValueAccess();
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}
	
	//Constants:
	//	'PI' | 'known' | 'e' | '--' | 'None' | 'a'? 'type' | DefiniteArticle? 'length' | 'count' | DefiniteArticle? 'index' |
	//	('first' | 'last' | AnArticle Ordinal?) 'element' | 'value';
	public SADLGrammarAccess.ConstantsElements getConstantsAccess() {
		return gaSADL.getConstantsAccess();
	}
	
	public ParserRule getConstantsRule() {
		return getConstantsAccess().getRule();
	}
	
	//ValueRow:
	//	explicitValues+=NestedExpression (',' explicitValues+=NestedExpression)*;
	public SADLGrammarAccess.ValueRowElements getValueRowAccess() {
		return gaSADL.getValueRowAccess();
	}
	
	public ParserRule getValueRowRule() {
		return getValueRowAccess().getRule();
	}
	
	//// e.g., George, 23, "Purple", 38.186111
	//DNAME:
	//	ID;
	public SADLGrammarAccess.DNAMEElements getDNAMEAccess() {
		return gaSADL.getDNAMEAccess();
	}
	
	public ParserRule getDNAMERule() {
		return getDNAMEAccess().getRule();
	}
	
	//AnyNumber ecore::EBigDecimal:
	//	DecimalNumber EXPONENT?;
	public SADLGrammarAccess.AnyNumberElements getAnyNumberAccess() {
		return gaSADL.getAnyNumberAccess();
	}
	
	public ParserRule getAnyNumberRule() {
		return getAnyNumberAccess().getRule();
	}
	
	//DecimalNumber ecore::EBigDecimal:
	//	NUMBER;
	public SADLGrammarAccess.DecimalNumberElements getDecimalNumberAccess() {
		return gaSADL.getDecimalNumberAccess();
	}
	
	public ParserRule getDecimalNumberRule() {
		return getDecimalNumberAccess().getRule();
	}
	
	//EXPONENT ecore::EBigDecimal:
	//	('e' | 'E') ('-' | '+')? DecimalNumber;
	public SADLGrammarAccess.EXPONENTElements getEXPONENTAccess() {
		return gaSADL.getEXPONENTAccess();
	}
	
	public ParserRule getEXPONENTRule() {
		return getEXPONENTAccess().getRule();
	}
	
	//EOS:
	//	'.';
	public SADLGrammarAccess.EOSElements getSADLEOSAccess() {
		return gaSADL.getEOSAccess();
	}
	
	public ParserRule getSADLEOSRule() {
		return getSADLEOSAccess().getRule();
	}
	
	//QNAME:
	//	QNAME_TERMINAL | ID;
	public SADLGrammarAccess.QNAMEElements getQNAMEAccess() {
		return gaSADL.getQNAMEAccess();
	}
	
	public ParserRule getQNAMERule() {
		return getQNAMEAccess().getRule();
	}
	
	//terminal NUMBER returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getNUMBERRule() {
		return gaSADL.getNUMBERRule();
	}
	
	//terminal WS:
	//	'\\u00A0' | ' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaSADL.getWSRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9' | '-' | '%' | '~')*;
	public TerminalRule getIDRule() {
		return gaSADL.getIDRule();
	}
	
	//terminal QNAME_TERMINAL:
	//	ID ':' ID;
	public TerminalRule getQNAME_TERMINALRule() {
		return gaSADL.getQNAME_TERMINALRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | 'u' | '"' | "'" | '\\') | !('\\' | '"'))* '"' |
	//	"'" ('\\' ('b' | 't' | 'n' | 'f' | 'r' | 'u' | '"' | "'" | '\\') | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaSADL.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaSADL.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaSADL.getSL_COMMENTRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaSADL.getANY_OTHERRule();
	}
}
