/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske;

import com.ge.research.sadl.darpa.aske.DialogStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DialogStandaloneSetup extends DialogStandaloneSetupGenerated {
  public static void doSetup() {
    new DialogStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
