/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske;

import com.ge.research.sadl.darpa.aske.AbstractDialogRuntimeModule;
import java.io.IOException;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parsetree.reconstr.IParseTreeConstructor;
import org.eclipse.xtext.parsetree.reconstr.ITokenStream;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DialogRuntimeModule extends AbstractDialogRuntimeModule {
  public static class NoImplParseTreeConstructor implements IParseTreeConstructor {
    @Override
    public IParseTreeConstructor.TreeConstructionReport serializeSubtree(final EObject object, final ITokenStream out) throws IOException {
      throw new UnsupportedOperationException("TODO: auto-generated method stub");
    }
  }
  
  public Class<? extends IParseTreeConstructor> bindIParseTreeConstructor() {
    return DialogRuntimeModule.NoImplParseTreeConstructor.class;
  }
}
