/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.scoping;

import com.ge.research.sadl.darpa.aske.scoping.AbstractDialogScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DialogScopeProvider extends AbstractDialogScopeProvider {
}
