swagger: "2.0"
info:
  description: "The following set of services can be used to extract triples related to scientific concepts and equations from text"
  version: "1.0.0"
  title: "DARPA AKSE TA 1 - ANSWER - Services for extracting knowledge from text"
  #termsOfService: "http://swagger.io/terms/"
  #contact:
  #  email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:4200"
basePath: "/v1"
tags:
- name: "text2triples"
  description: "everything about text to triples"
schemes:
- "https"
- "http"
paths:
  /text2triples:
    post:
      tags:
      - "text2triples"
      operationId: "app.text_to_triples"
      consumes:
      - application/json
      produces: 
      - application/json
      parameters: 
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Text"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Triples"
        405:
          description: "Invalid input"
definitions:
  Text:
    type: "object"
    required: 
    - "text"
    - "locality"
    properties:
      text:
        type: "string"
      locality:
        type: "string"
    xml:
      name: "Text"
  Triple:
    type: "object"
    required:
    - "subject"
    - "predicate"
    - "object"
    - "confScore"
    properties:
      subject:
        type: "string"
      predicate:
        type: "string"
      object:
        type: "string"
      confScore:
        type: "number"
        format: "double"
  Triples:
    type: "object"
    required: 
    - "text"
    - "triples"
    properties:
      text:
        type: "string"
      triples:
        type: "array"
        items:
          $ref: "#/definitions/Triple"
externalDocs:
  description: "Find out more about the ANSWER system"
  url: "https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/wiki"