/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.dialog.impl;

import com.ge.research.sadl.darpa.aske.dialog.DialogFactory;
import com.ge.research.sadl.darpa.aske.dialog.DialogPackage;
import com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement;
import com.ge.research.sadl.darpa.aske.dialog.ModifiedAskStatement;
import com.ge.research.sadl.darpa.aske.dialog.StringResponse;
import com.ge.research.sadl.darpa.aske.dialog.WhatIsStatement;
import com.ge.research.sadl.darpa.aske.dialog.WhatStatement;
import com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement;

import com.ge.research.sadl.sADL.SADLPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DialogPackageImpl extends EPackageImpl implements DialogPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringResponseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass whatStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass whatIsStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass whatValuesStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass howManyValuesStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modifiedAskStatementEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private DialogPackageImpl()
  {
    super(eNS_URI, DialogFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link DialogPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static DialogPackage init()
  {
    if (isInited) return (DialogPackage)EPackage.Registry.INSTANCE.getEPackage(DialogPackage.eNS_URI);

    // Obtain or create and register package
    DialogPackageImpl theDialogPackage = (DialogPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof DialogPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new DialogPackageImpl());

    isInited = true;

    // Initialize simple dependencies
    SADLPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theDialogPackage.createPackageContents();

    // Initialize created meta-data
    theDialogPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theDialogPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(DialogPackage.eNS_URI, theDialogPackage);
    return theDialogPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getStringResponse()
  {
    return stringResponseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getStringResponse_Str()
  {
    return (EAttribute)stringResponseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWhatStatement()
  {
    return whatStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWhatStatement_Stmt()
  {
    return (EReference)whatStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWhatIsStatement()
  {
    return whatIsStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWhatIsStatement_Article()
  {
    return (EAttribute)whatIsStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWhatIsStatement_Target()
  {
    return (EReference)whatIsStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWhatValuesStatement()
  {
    return whatValuesStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWhatValuesStatement_Typ()
  {
    return (EAttribute)whatValuesStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWhatValuesStatement_Prop()
  {
    return (EReference)whatValuesStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWhatValuesStatement_Article()
  {
    return (EAttribute)whatValuesStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWhatValuesStatement_Cls()
  {
    return (EReference)whatValuesStatementEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getHowManyValuesStatement()
  {
    return howManyValuesStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getHowManyValuesStatement_Prop()
  {
    return (EReference)howManyValuesStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getHowManyValuesStatement_Typ()
  {
    return (EReference)howManyValuesStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getHowManyValuesStatement_Article()
  {
    return (EAttribute)howManyValuesStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getHowManyValuesStatement_Cls()
  {
    return (EReference)howManyValuesStatementEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModifiedAskStatement()
  {
    return modifiedAskStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModifiedAskStatement_Expr()
  {
    return (EReference)modifiedAskStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DialogFactory getDialogFactory()
  {
    return (DialogFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    stringResponseEClass = createEClass(STRING_RESPONSE);
    createEAttribute(stringResponseEClass, STRING_RESPONSE__STR);

    whatStatementEClass = createEClass(WHAT_STATEMENT);
    createEReference(whatStatementEClass, WHAT_STATEMENT__STMT);

    whatIsStatementEClass = createEClass(WHAT_IS_STATEMENT);
    createEAttribute(whatIsStatementEClass, WHAT_IS_STATEMENT__ARTICLE);
    createEReference(whatIsStatementEClass, WHAT_IS_STATEMENT__TARGET);

    whatValuesStatementEClass = createEClass(WHAT_VALUES_STATEMENT);
    createEAttribute(whatValuesStatementEClass, WHAT_VALUES_STATEMENT__TYP);
    createEReference(whatValuesStatementEClass, WHAT_VALUES_STATEMENT__PROP);
    createEAttribute(whatValuesStatementEClass, WHAT_VALUES_STATEMENT__ARTICLE);
    createEReference(whatValuesStatementEClass, WHAT_VALUES_STATEMENT__CLS);

    howManyValuesStatementEClass = createEClass(HOW_MANY_VALUES_STATEMENT);
    createEReference(howManyValuesStatementEClass, HOW_MANY_VALUES_STATEMENT__PROP);
    createEReference(howManyValuesStatementEClass, HOW_MANY_VALUES_STATEMENT__TYP);
    createEAttribute(howManyValuesStatementEClass, HOW_MANY_VALUES_STATEMENT__ARTICLE);
    createEReference(howManyValuesStatementEClass, HOW_MANY_VALUES_STATEMENT__CLS);

    modifiedAskStatementEClass = createEClass(MODIFIED_ASK_STATEMENT);
    createEReference(modifiedAskStatementEClass, MODIFIED_ASK_STATEMENT__EXPR);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    SADLPackage theSADLPackage = (SADLPackage)EPackage.Registry.INSTANCE.getEPackage(SADLPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    stringResponseEClass.getESuperTypes().add(theSADLPackage.getSadlModelElement());
    whatStatementEClass.getESuperTypes().add(theSADLPackage.getSadlModelElement());
    howManyValuesStatementEClass.getESuperTypes().add(theSADLPackage.getSadlModelElement());
    modifiedAskStatementEClass.getESuperTypes().add(theSADLPackage.getExpressionScope());

    // Initialize classes and features; add operations and parameters
    initEClass(stringResponseEClass, StringResponse.class, "StringResponse", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStringResponse_Str(), ecorePackage.getEString(), "str", null, 0, 1, StringResponse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(whatStatementEClass, WhatStatement.class, "WhatStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getWhatStatement_Stmt(), ecorePackage.getEObject(), null, "stmt", null, 0, 1, WhatStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(whatIsStatementEClass, WhatIsStatement.class, "WhatIsStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWhatIsStatement_Article(), ecorePackage.getEString(), "article", null, 0, 1, WhatIsStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getWhatIsStatement_Target(), theSADLPackage.getSadlResource(), null, "target", null, 0, 1, WhatIsStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(whatValuesStatementEClass, WhatValuesStatement.class, "WhatValuesStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWhatValuesStatement_Typ(), ecorePackage.getEString(), "typ", null, 0, 1, WhatValuesStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getWhatValuesStatement_Prop(), theSADLPackage.getSadlResource(), null, "prop", null, 0, 1, WhatValuesStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getWhatValuesStatement_Article(), ecorePackage.getEString(), "article", null, 0, 1, WhatValuesStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getWhatValuesStatement_Cls(), theSADLPackage.getSadlTypeReference(), null, "cls", null, 0, 1, WhatValuesStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(howManyValuesStatementEClass, HowManyValuesStatement.class, "HowManyValuesStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getHowManyValuesStatement_Prop(), theSADLPackage.getSadlResource(), null, "prop", null, 0, 1, HowManyValuesStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getHowManyValuesStatement_Typ(), theSADLPackage.getSadlTypeReference(), null, "typ", null, 0, 1, HowManyValuesStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getHowManyValuesStatement_Article(), ecorePackage.getEString(), "article", null, 0, 1, HowManyValuesStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getHowManyValuesStatement_Cls(), theSADLPackage.getSadlTypeReference(), null, "cls", null, 0, 1, HowManyValuesStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modifiedAskStatementEClass, ModifiedAskStatement.class, "ModifiedAskStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModifiedAskStatement_Expr(), theSADLPackage.getExpression(), null, "expr", null, 0, 1, ModifiedAskStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //DialogPackageImpl
