/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.dialog.impl;

import com.ge.research.sadl.darpa.aske.dialog.DialogPackage;
import com.ge.research.sadl.darpa.aske.dialog.ResponseStatement;

import com.ge.research.sadl.sADL.SadlModelElement;

import com.ge.research.sadl.sADL.impl.SadlModelElementImpl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Response Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.impl.ResponseStatementImpl#getSstmt <em>Sstmt</em>}</li>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.impl.ResponseStatementImpl#getStr <em>Str</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ResponseStatementImpl extends SadlModelElementImpl implements ResponseStatement
{
  /**
   * The cached value of the '{@link #getSstmt() <em>Sstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSstmt()
   * @generated
   * @ordered
   */
  protected SadlModelElement sstmt;

  /**
   * The default value of the '{@link #getStr() <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr()
   * @generated
   * @ordered
   */
  protected static final String STR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStr() <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStr()
   * @generated
   * @ordered
   */
  protected String str = STR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResponseStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DialogPackage.Literals.RESPONSE_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SadlModelElement getSstmt()
  {
    return sstmt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSstmt(SadlModelElement newSstmt, NotificationChain msgs)
  {
    SadlModelElement oldSstmt = sstmt;
    sstmt = newSstmt;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DialogPackage.RESPONSE_STATEMENT__SSTMT, oldSstmt, newSstmt);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSstmt(SadlModelElement newSstmt)
  {
    if (newSstmt != sstmt)
    {
      NotificationChain msgs = null;
      if (sstmt != null)
        msgs = ((InternalEObject)sstmt).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DialogPackage.RESPONSE_STATEMENT__SSTMT, null, msgs);
      if (newSstmt != null)
        msgs = ((InternalEObject)newSstmt).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DialogPackage.RESPONSE_STATEMENT__SSTMT, null, msgs);
      msgs = basicSetSstmt(newSstmt, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DialogPackage.RESPONSE_STATEMENT__SSTMT, newSstmt, newSstmt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStr()
  {
    return str;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStr(String newStr)
  {
    String oldStr = str;
    str = newStr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DialogPackage.RESPONSE_STATEMENT__STR, oldStr, str));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DialogPackage.RESPONSE_STATEMENT__SSTMT:
        return basicSetSstmt(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DialogPackage.RESPONSE_STATEMENT__SSTMT:
        return getSstmt();
      case DialogPackage.RESPONSE_STATEMENT__STR:
        return getStr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DialogPackage.RESPONSE_STATEMENT__SSTMT:
        setSstmt((SadlModelElement)newValue);
        return;
      case DialogPackage.RESPONSE_STATEMENT__STR:
        setStr((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DialogPackage.RESPONSE_STATEMENT__SSTMT:
        setSstmt((SadlModelElement)null);
        return;
      case DialogPackage.RESPONSE_STATEMENT__STR:
        setStr(STR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DialogPackage.RESPONSE_STATEMENT__SSTMT:
        return sstmt != null;
      case DialogPackage.RESPONSE_STATEMENT__STR:
        return STR_EDEFAULT == null ? str != null : !STR_EDEFAULT.equals(str);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (str: ");
    result.append(str);
    result.append(')');
    return result.toString();
  }

} //ResponseStatementImpl
