/*
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.scoping;

import com.ge.research.sadl.scoping.SADLScopeProvider;

public abstract class AbstractDialogScopeProvider extends SADLScopeProvider {
}
