/*
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.validation;

import com.ge.research.sadl.validation.SADLValidator;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public abstract class AbstractDialogValidator extends SADLValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(com.ge.research.sadl.darpa.aske.dialog.DialogPackage.eINSTANCE);
		return result;
	}
}
