/*
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.ui.tests;

import com.ge.research.sadl.darpa.aske.dialog.ui.internal.DialogActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DialogUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DialogActivator.getInstance().getInjector("com.ge.research.sadl.darpa.aske.Dialog");
	}

}
