/*
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.ui;

import com.ge.research.sadl.darpa.aske.dialog.ui.internal.DialogActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DialogExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DialogActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DialogActivator activator = DialogActivator.getInstance();
		return activator != null ? activator.getInjector(DialogActivator.COM_GE_RESEARCH_SADL_DARPA_ASKE_DIALOG) : null;
	}

}
