/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.ui.contentassist;

import com.ge.research.sadl.darpa.aske.ui.contentassist.AbstractDialogProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DialogProposalProvider extends AbstractDialogProposalProvider {
}
