/*
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DialogStandaloneSetup extends DialogStandaloneSetupGenerated {

	def static void doSetup() {
		new DialogStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
