/*
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.parser.antlr;

import com.ge.research.sadl.darpa.aske.parser.antlr.internal.InternalDialogParser;
import com.ge.research.sadl.darpa.aske.services.DialogGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DialogParser extends AbstractAntlrParser {

	@Inject
	private DialogGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDialogParser createParser(XtextTokenStream stream) {
		return new InternalDialogParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DialogModel";
	}

	public DialogGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DialogGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
