/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.dialog;

import com.ge.research.sadl.sADL.ExpressionScope;
import com.ge.research.sadl.sADL.SadlTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.DialogQuestion#getArticle <em>Article</em>}</li>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.DialogQuestion#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getDialogQuestion()
 * @model
 * @generated
 */
public interface DialogQuestion extends ExpressionScope
{
  /**
   * Returns the value of the '<em><b>Article</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Article</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Article</em>' attribute.
   * @see #setArticle(String)
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getDialogQuestion_Article()
   * @model
   * @generated
   */
  String getArticle();

  /**
   * Sets the value of the '{@link com.ge.research.sadl.darpa.aske.dialog.DialogQuestion#getArticle <em>Article</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Article</em>' attribute.
   * @see #getArticle()
   * @generated
   */
  void setArticle(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(SadlTypeReference)
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getDialogQuestion_Target()
   * @model containment="true"
   * @generated
   */
  SadlTypeReference getTarget();

  /**
   * Sets the value of the '{@link com.ge.research.sadl.darpa.aske.dialog.DialogQuestion#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(SadlTypeReference value);

} // DialogQuestion
