/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.dialog;

import com.ge.research.sadl.sADL.SADLPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.ge.research.sadl.darpa.aske.dialog.DialogFactory
 * @model kind="package"
 * @generated
 */
public interface DialogPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dialog";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ge.com/research/sadl/darpa/aske/Dialog";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dialog";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DialogPackage eINSTANCE = com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl.init();

  /**
   * The meta object id for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.ResponseStatementImpl <em>Response Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.ResponseStatementImpl
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getResponseStatement()
   * @generated
   */
  int RESPONSE_STATEMENT = 0;

  /**
   * The feature id for the '<em><b>Sstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE_STATEMENT__SSTMT = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE_STATEMENT__STR = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Response Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE_STATEMENT_FEATURE_COUNT = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.StringResponseImpl <em>String Response</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.StringResponseImpl
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getStringResponse()
   * @generated
   */
  int STRING_RESPONSE = 1;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_RESPONSE__STR = 0;

  /**
   * The number of structural features of the '<em>String Response</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_RESPONSE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.WhatStatementImpl <em>What Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.WhatStatementImpl
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getWhatStatement()
   * @generated
   */
  int WHAT_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_STATEMENT__STMT = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>What Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_STATEMENT_FEATURE_COUNT = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.WhatIsStatementImpl <em>What Is Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.WhatIsStatementImpl
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getWhatIsStatement()
   * @generated
   */
  int WHAT_IS_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Article</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_IS_STATEMENT__ARTICLE = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_IS_STATEMENT__TARGET = 1;

  /**
   * The number of structural features of the '<em>What Is Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_IS_STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.WhatValuesStatementImpl <em>What Values Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.WhatValuesStatementImpl
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getWhatValuesStatement()
   * @generated
   */
  int WHAT_VALUES_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Typ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_VALUES_STATEMENT__TYP = 0;

  /**
   * The feature id for the '<em><b>Prop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_VALUES_STATEMENT__PROP = 1;

  /**
   * The feature id for the '<em><b>Article</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_VALUES_STATEMENT__ARTICLE = 2;

  /**
   * The feature id for the '<em><b>Cls</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_VALUES_STATEMENT__CLS = 3;

  /**
   * The number of structural features of the '<em>What Values Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHAT_VALUES_STATEMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.HowManyValuesStatementImpl <em>How Many Values Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.HowManyValuesStatementImpl
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getHowManyValuesStatement()
   * @generated
   */
  int HOW_MANY_VALUES_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>Prop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOW_MANY_VALUES_STATEMENT__PROP = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Typ</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOW_MANY_VALUES_STATEMENT__TYP = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Article</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOW_MANY_VALUES_STATEMENT__ARTICLE = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Cls</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOW_MANY_VALUES_STATEMENT__CLS = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>How Many Values Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOW_MANY_VALUES_STATEMENT_FEATURE_COUNT = SADLPackage.SADL_MODEL_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.ModifiedAskStatementImpl <em>Modified Ask Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.ModifiedAskStatementImpl
   * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getModifiedAskStatement()
   * @generated
   */
  int MODIFIED_ASK_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFIED_ASK_STATEMENT__START = SADLPackage.EXPRESSION_SCOPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFIED_ASK_STATEMENT__EXPR = SADLPackage.EXPRESSION_SCOPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Modified Ask Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFIED_ASK_STATEMENT_FEATURE_COUNT = SADLPackage.EXPRESSION_SCOPE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link com.ge.research.sadl.darpa.aske.dialog.ResponseStatement <em>Response Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Response Statement</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.ResponseStatement
   * @generated
   */
  EClass getResponseStatement();

  /**
   * Returns the meta object for the containment reference '{@link com.ge.research.sadl.darpa.aske.dialog.ResponseStatement#getSstmt <em>Sstmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sstmt</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.ResponseStatement#getSstmt()
   * @see #getResponseStatement()
   * @generated
   */
  EReference getResponseStatement_Sstmt();

  /**
   * Returns the meta object for the attribute '{@link com.ge.research.sadl.darpa.aske.dialog.ResponseStatement#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.ResponseStatement#getStr()
   * @see #getResponseStatement()
   * @generated
   */
  EAttribute getResponseStatement_Str();

  /**
   * Returns the meta object for class '{@link com.ge.research.sadl.darpa.aske.dialog.StringResponse <em>String Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Response</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.StringResponse
   * @generated
   */
  EClass getStringResponse();

  /**
   * Returns the meta object for the attribute '{@link com.ge.research.sadl.darpa.aske.dialog.StringResponse#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.StringResponse#getStr()
   * @see #getStringResponse()
   * @generated
   */
  EAttribute getStringResponse_Str();

  /**
   * Returns the meta object for class '{@link com.ge.research.sadl.darpa.aske.dialog.WhatStatement <em>What Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>What Statement</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatStatement
   * @generated
   */
  EClass getWhatStatement();

  /**
   * Returns the meta object for the containment reference '{@link com.ge.research.sadl.darpa.aske.dialog.WhatStatement#getStmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatStatement#getStmt()
   * @see #getWhatStatement()
   * @generated
   */
  EReference getWhatStatement_Stmt();

  /**
   * Returns the meta object for class '{@link com.ge.research.sadl.darpa.aske.dialog.WhatIsStatement <em>What Is Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>What Is Statement</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatIsStatement
   * @generated
   */
  EClass getWhatIsStatement();

  /**
   * Returns the meta object for the attribute '{@link com.ge.research.sadl.darpa.aske.dialog.WhatIsStatement#getArticle <em>Article</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Article</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatIsStatement#getArticle()
   * @see #getWhatIsStatement()
   * @generated
   */
  EAttribute getWhatIsStatement_Article();

  /**
   * Returns the meta object for the containment reference '{@link com.ge.research.sadl.darpa.aske.dialog.WhatIsStatement#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatIsStatement#getTarget()
   * @see #getWhatIsStatement()
   * @generated
   */
  EReference getWhatIsStatement_Target();

  /**
   * Returns the meta object for class '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement <em>What Values Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>What Values Statement</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement
   * @generated
   */
  EClass getWhatValuesStatement();

  /**
   * Returns the meta object for the attribute '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getTyp <em>Typ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Typ</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getTyp()
   * @see #getWhatValuesStatement()
   * @generated
   */
  EAttribute getWhatValuesStatement_Typ();

  /**
   * Returns the meta object for the containment reference '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getProp <em>Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prop</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getProp()
   * @see #getWhatValuesStatement()
   * @generated
   */
  EReference getWhatValuesStatement_Prop();

  /**
   * Returns the meta object for the attribute '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getArticle <em>Article</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Article</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getArticle()
   * @see #getWhatValuesStatement()
   * @generated
   */
  EAttribute getWhatValuesStatement_Article();

  /**
   * Returns the meta object for the containment reference '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getCls <em>Cls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cls</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getCls()
   * @see #getWhatValuesStatement()
   * @generated
   */
  EReference getWhatValuesStatement_Cls();

  /**
   * Returns the meta object for class '{@link com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement <em>How Many Values Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>How Many Values Statement</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement
   * @generated
   */
  EClass getHowManyValuesStatement();

  /**
   * Returns the meta object for the containment reference '{@link com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement#getProp <em>Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prop</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement#getProp()
   * @see #getHowManyValuesStatement()
   * @generated
   */
  EReference getHowManyValuesStatement_Prop();

  /**
   * Returns the meta object for the containment reference '{@link com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement#getTyp <em>Typ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Typ</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement#getTyp()
   * @see #getHowManyValuesStatement()
   * @generated
   */
  EReference getHowManyValuesStatement_Typ();

  /**
   * Returns the meta object for the attribute '{@link com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement#getArticle <em>Article</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Article</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement#getArticle()
   * @see #getHowManyValuesStatement()
   * @generated
   */
  EAttribute getHowManyValuesStatement_Article();

  /**
   * Returns the meta object for the containment reference '{@link com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement#getCls <em>Cls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cls</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.HowManyValuesStatement#getCls()
   * @see #getHowManyValuesStatement()
   * @generated
   */
  EReference getHowManyValuesStatement_Cls();

  /**
   * Returns the meta object for class '{@link com.ge.research.sadl.darpa.aske.dialog.ModifiedAskStatement <em>Modified Ask Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modified Ask Statement</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.ModifiedAskStatement
   * @generated
   */
  EClass getModifiedAskStatement();

  /**
   * Returns the meta object for the attribute '{@link com.ge.research.sadl.darpa.aske.dialog.ModifiedAskStatement#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.ModifiedAskStatement#getStart()
   * @see #getModifiedAskStatement()
   * @generated
   */
  EAttribute getModifiedAskStatement_Start();

  /**
   * Returns the meta object for the containment reference '{@link com.ge.research.sadl.darpa.aske.dialog.ModifiedAskStatement#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see com.ge.research.sadl.darpa.aske.dialog.ModifiedAskStatement#getExpr()
   * @see #getModifiedAskStatement()
   * @generated
   */
  EReference getModifiedAskStatement_Expr();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DialogFactory getDialogFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.ResponseStatementImpl <em>Response Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.ResponseStatementImpl
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getResponseStatement()
     * @generated
     */
    EClass RESPONSE_STATEMENT = eINSTANCE.getResponseStatement();

    /**
     * The meta object literal for the '<em><b>Sstmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESPONSE_STATEMENT__SSTMT = eINSTANCE.getResponseStatement_Sstmt();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESPONSE_STATEMENT__STR = eINSTANCE.getResponseStatement_Str();

    /**
     * The meta object literal for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.StringResponseImpl <em>String Response</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.StringResponseImpl
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getStringResponse()
     * @generated
     */
    EClass STRING_RESPONSE = eINSTANCE.getStringResponse();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_RESPONSE__STR = eINSTANCE.getStringResponse_Str();

    /**
     * The meta object literal for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.WhatStatementImpl <em>What Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.WhatStatementImpl
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getWhatStatement()
     * @generated
     */
    EClass WHAT_STATEMENT = eINSTANCE.getWhatStatement();

    /**
     * The meta object literal for the '<em><b>Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHAT_STATEMENT__STMT = eINSTANCE.getWhatStatement_Stmt();

    /**
     * The meta object literal for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.WhatIsStatementImpl <em>What Is Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.WhatIsStatementImpl
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getWhatIsStatement()
     * @generated
     */
    EClass WHAT_IS_STATEMENT = eINSTANCE.getWhatIsStatement();

    /**
     * The meta object literal for the '<em><b>Article</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHAT_IS_STATEMENT__ARTICLE = eINSTANCE.getWhatIsStatement_Article();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHAT_IS_STATEMENT__TARGET = eINSTANCE.getWhatIsStatement_Target();

    /**
     * The meta object literal for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.WhatValuesStatementImpl <em>What Values Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.WhatValuesStatementImpl
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getWhatValuesStatement()
     * @generated
     */
    EClass WHAT_VALUES_STATEMENT = eINSTANCE.getWhatValuesStatement();

    /**
     * The meta object literal for the '<em><b>Typ</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHAT_VALUES_STATEMENT__TYP = eINSTANCE.getWhatValuesStatement_Typ();

    /**
     * The meta object literal for the '<em><b>Prop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHAT_VALUES_STATEMENT__PROP = eINSTANCE.getWhatValuesStatement_Prop();

    /**
     * The meta object literal for the '<em><b>Article</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHAT_VALUES_STATEMENT__ARTICLE = eINSTANCE.getWhatValuesStatement_Article();

    /**
     * The meta object literal for the '<em><b>Cls</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHAT_VALUES_STATEMENT__CLS = eINSTANCE.getWhatValuesStatement_Cls();

    /**
     * The meta object literal for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.HowManyValuesStatementImpl <em>How Many Values Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.HowManyValuesStatementImpl
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getHowManyValuesStatement()
     * @generated
     */
    EClass HOW_MANY_VALUES_STATEMENT = eINSTANCE.getHowManyValuesStatement();

    /**
     * The meta object literal for the '<em><b>Prop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOW_MANY_VALUES_STATEMENT__PROP = eINSTANCE.getHowManyValuesStatement_Prop();

    /**
     * The meta object literal for the '<em><b>Typ</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOW_MANY_VALUES_STATEMENT__TYP = eINSTANCE.getHowManyValuesStatement_Typ();

    /**
     * The meta object literal for the '<em><b>Article</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOW_MANY_VALUES_STATEMENT__ARTICLE = eINSTANCE.getHowManyValuesStatement_Article();

    /**
     * The meta object literal for the '<em><b>Cls</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOW_MANY_VALUES_STATEMENT__CLS = eINSTANCE.getHowManyValuesStatement_Cls();

    /**
     * The meta object literal for the '{@link com.ge.research.sadl.darpa.aske.dialog.impl.ModifiedAskStatementImpl <em>Modified Ask Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.ModifiedAskStatementImpl
     * @see com.ge.research.sadl.darpa.aske.dialog.impl.DialogPackageImpl#getModifiedAskStatement()
     * @generated
     */
    EClass MODIFIED_ASK_STATEMENT = eINSTANCE.getModifiedAskStatement();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODIFIED_ASK_STATEMENT__START = eINSTANCE.getModifiedAskStatement_Start();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODIFIED_ASK_STATEMENT__EXPR = eINSTANCE.getModifiedAskStatement_Expr();

  }

} //DialogPackage
