/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.dialog;

import com.ge.research.sadl.sADL.SadlModelElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Response Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.ResponseStatement#getSstmt <em>Sstmt</em>}</li>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.ResponseStatement#getStr <em>Str</em>}</li>
 * </ul>
 *
 * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getResponseStatement()
 * @model
 * @generated
 */
public interface ResponseStatement extends SadlModelElement
{
  /**
   * Returns the value of the '<em><b>Sstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sstmt</em>' containment reference.
   * @see #setSstmt(SadlModelElement)
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getResponseStatement_Sstmt()
   * @model containment="true"
   * @generated
   */
  SadlModelElement getSstmt();

  /**
   * Sets the value of the '{@link com.ge.research.sadl.darpa.aske.dialog.ResponseStatement#getSstmt <em>Sstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sstmt</em>' containment reference.
   * @see #getSstmt()
   * @generated
   */
  void setSstmt(SadlModelElement value);

  /**
   * Returns the value of the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Str</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str</em>' attribute.
   * @see #setStr(String)
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getResponseStatement_Str()
   * @model
   * @generated
   */
  String getStr();

  /**
   * Sets the value of the '{@link com.ge.research.sadl.darpa.aske.dialog.ResponseStatement#getStr <em>Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str</em>' attribute.
   * @see #getStr()
   * @generated
   */
  void setStr(String value);

} // ResponseStatement
