/**
 * generated by Xtext 2.14.0.RC1
 */
package com.ge.research.sadl.darpa.aske.dialog;

import com.ge.research.sadl.sADL.SadlResource;
import com.ge.research.sadl.sADL.SadlTypeReference;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>What Values Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getTypof <em>Typof</em>}</li>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getTyp <em>Typ</em>}</li>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getProp <em>Prop</em>}</li>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getArticle <em>Article</em>}</li>
 *   <li>{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getCls <em>Cls</em>}</li>
 * </ul>
 *
 * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getWhatValuesStatement()
 * @model
 * @generated
 */
public interface WhatValuesStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Typof</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typof</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typof</em>' attribute.
   * @see #setTypof(String)
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getWhatValuesStatement_Typof()
   * @model
   * @generated
   */
  String getTypof();

  /**
   * Sets the value of the '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getTypof <em>Typof</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typof</em>' attribute.
   * @see #getTypof()
   * @generated
   */
  void setTypof(String value);

  /**
   * Returns the value of the '<em><b>Typ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typ</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typ</em>' attribute.
   * @see #setTyp(String)
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getWhatValuesStatement_Typ()
   * @model
   * @generated
   */
  String getTyp();

  /**
   * Sets the value of the '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getTyp <em>Typ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typ</em>' attribute.
   * @see #getTyp()
   * @generated
   */
  void setTyp(String value);

  /**
   * Returns the value of the '<em><b>Prop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prop</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop</em>' containment reference.
   * @see #setProp(SadlResource)
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getWhatValuesStatement_Prop()
   * @model containment="true"
   * @generated
   */
  SadlResource getProp();

  /**
   * Sets the value of the '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getProp <em>Prop</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prop</em>' containment reference.
   * @see #getProp()
   * @generated
   */
  void setProp(SadlResource value);

  /**
   * Returns the value of the '<em><b>Article</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Article</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Article</em>' attribute.
   * @see #setArticle(String)
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getWhatValuesStatement_Article()
   * @model
   * @generated
   */
  String getArticle();

  /**
   * Sets the value of the '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getArticle <em>Article</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Article</em>' attribute.
   * @see #getArticle()
   * @generated
   */
  void setArticle(String value);

  /**
   * Returns the value of the '<em><b>Cls</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cls</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cls</em>' containment reference.
   * @see #setCls(SadlTypeReference)
   * @see com.ge.research.sadl.darpa.aske.dialog.DialogPackage#getWhatValuesStatement_Cls()
   * @model containment="true"
   * @generated
   */
  SadlTypeReference getCls();

  /**
   * Sets the value of the '{@link com.ge.research.sadl.darpa.aske.dialog.WhatValuesStatement#getCls <em>Cls</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cls</em>' containment reference.
   * @see #getCls()
   * @generated
   */
  void setCls(SadlTypeReference value);

} // WhatValuesStatement
